# Generated by Django 4.2.1 on 2023-05-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripcion del articulo', max_length=100)),
                ('codigo', models.PositiveBigIntegerField(help_text='codigo')),
                ('costo', models.DecimalField(decimal_places=50, max_digits=50)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.BigIntegerField(help_text='Cantidad de articulos')),
                ('talle', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('direccion', models.CharField(help_text='Direccion del proveedor', max_length=100)),
                ('DNI', models.PositiveBigIntegerField(help_text='Dni del cliente')),
                ('telefono', models.PositiveBigIntegerField(help_text='Telefono del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='compraProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(help_text='cantidad de articulos')),
                ('precio', models.DecimalField(decimal_places=50, max_digits=50)),
                ('idArticulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de compra')),
                ('articulos', models.ManyToManyField(related_name='articulos_comprados', through='appRieVictoria.compraProd', to='appRieVictoria.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del empleado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ventaProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(help_text='Cantidad de ventas')),
                ('precio', models.DecimalField(decimal_places=50, max_digits=50)),
                ('idArticulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.articulos')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de compra')),
                ('tipo', models.CharField(help_text='Tipo de factura', max_length=10)),
                ('articulos', models.ManyToManyField(related_name='ventas_productos', through='appRieVictoria.ventaProd', to='appRieVictoria.articulos')),
                ('idClientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.clientes')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='ventaprod',
            name='idVenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.ventas'),
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=50)),
                ('direccion', models.CharField(help_text='Direccion del proveedor', max_length=100)),
                ('Email', models.EmailField(help_text='Email del proveedor', max_length=254)),
                ('cuit', models.PositiveBigIntegerField(help_text='Cuit del proveedor')),
                ('telefono', models.PositiveBigIntegerField()),
                ('empleados', models.ManyToManyField(related_name='empleados_compran_a_proveedores', through='appRieVictoria.Compras', to='appRieVictoria.empleados')),
            ],
        ),
        migrations.AddField(
            model_name='empleados',
            name='clientes',
            field=models.ManyToManyField(related_name='empleados_relacionados', through='appRieVictoria.Ventas', to='appRieVictoria.clientes'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='proveedores',
            field=models.ManyToManyField(related_name='venden_a_empleados', through='appRieVictoria.Compras', to='appRieVictoria.proveedores'),
        ),
        migrations.AddField(
            model_name='compras',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.empleados'),
        ),
        migrations.AddField(
            model_name='compras',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.proveedores'),
        ),
        migrations.AddField(
            model_name='compraprod',
            name='idCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.compras'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='empleados',
            field=models.ManyToManyField(related_name='clientes_relacionados', through='appRieVictoria.Ventas', to='appRieVictoria.empleados'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='compras',
            field=models.ManyToManyField(related_name='articulos_comprados', through='appRieVictoria.compraProd', to='appRieVictoria.compras'),
        ),
        migrations.AddField(
            model_name='articulos',
            name='ventas',
            field=models.ManyToManyField(related_name='articulos_vendidos', through='appRieVictoria.ventaProd', to='appRieVictoria.ventas'),
        ),
    ]
