# Generated by Django 4.2.1 on 2023-05-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='talle',
            field=models.CharField(max_length=3),
        ),
    ]
