# Generated by Django 4.2.1 on 2023-05-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0002_alter_articulos_costo_alter_articulos_talle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Tipo de articulo', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='codigo',
        ),
        migrations.AddField(
            model_name='articulos',
            name='tipoPrenda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.tipoprenda'),
        ),
    ]
