# Generated by Django 4.2.1 on 2023-05-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0003_tipoprenda_remove_articulos_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Tipo de factura', max_length=2)),
            ],
        ),
    ]
