# Generated by Django 4.2.1 on 2023-05-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0004_tipofactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='tipoFactura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.tipofactura'),
        ),
    ]
