# Generated by Django 4.2.1 on 2023-05-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0005_ventas_tipofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='tipo',
        ),
    ]
