# Generated by Django 4.2.1 on 2023-05-24 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0007_alter_ventas_tipofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(help_text='Nombre del empleado', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cuit',
            field=models.PositiveBigIntegerField(help_text='Cuit del proveedor', verbose_name='Cuit'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(help_text='Direccion del proveedor', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='empleados',
            field=models.ManyToManyField(related_name='empleados_compran_a_proveedores', through='appRieVictoria.Compras', to='appRieVictoria.empleados', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(help_text='Nombre del proveedor', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(help_text='Fecha de venta', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='idClientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='idEmpleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appRieVictoria.empleados', verbose_name='Empleado'),
        ),
    ]
