# Generated by Django 4.2.1 on 2023-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0008_alter_empleados_nombre_alter_proveedores_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaprod',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
