# Generated by Django 4.2.1 on 2023-07-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0009_alter_ventaprod_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraprod',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
