# Generated by Django 4.2.1 on 2023-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0010_alter_compraprod_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='Email',
            field=models.EmailField(default=1, help_text='Email del empleado', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(default=1, help_text='Direccion del empleado', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='telefono',
            field=models.PositiveBigIntegerField(default=1, help_text='Telefono del empleado'),
            preserve_default=False,
        ),
    ]
