# Generated by Django 4.2.1 on 2023-08-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0011_empleados_email_empleados_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(help_text='Nombre del proveedor', max_length=25, verbose_name='Nombre'),
        ),
    ]
