# Generated by Django 4.2.1 on 2023-10-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0012_alter_proveedores_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='compras',
            field=models.ManyToManyField(related_name='articulos_comprados', through='appRieVictoria.CompraProd', to='appRieVictoria.compras'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='ventas',
            field=models.ManyToManyField(related_name='articulos_vendidos', through='appRieVictoria.VentaProd', to='appRieVictoria.ventas'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='articulos',
            field=models.ManyToManyField(related_name='articulos_comprados', through='appRieVictoria.CompraProd', to='appRieVictoria.articulos'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='articulos',
            field=models.ManyToManyField(related_name='ventas_productos', through='appRieVictoria.VentaProd', to='appRieVictoria.articulos'),
        ),
    ]
