# Generated by Django 4.2.1 on 2023-10-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0013_alter_articulos_compras_alter_articulos_ventas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaprod',
            name='precio',
        ),
    ]
