# Generated by Django 4.2.1 on 2023-10-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0014_remove_ventaprod_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaprod',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventaprod',
            name='totalVenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
