# Generated by Django 4.2.1 on 2023-10-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0015_ventaprod_precioventa_ventaprod_totalventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraprod',
            name='totalCompra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
