# Generated by Django 4.2.1 on 2023-11-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0017_remove_articulos_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
