# Generated by Django 4.2.1 on 2023-11-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0018_articulos_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='costo',
        ),
    ]
