# Generated by Django 4.2.1 on 2023-11-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0019_remove_articulos_costo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'permissions': [('puede_aprobar', 'Puede aprobar el modelo'), ('puede_publicar', 'Puede publicar el modelo')]},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'permissions': [('puede_aprobar', 'Puede aprobar el modelo'), ('puede_publicar', 'Puede publicar el modelo')]},
        ),
    ]
