# Generated by Django 4.2.1 on 2023-11-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0020_alter_empleados_options_alter_proveedores_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='compras',
        ),
        migrations.RemoveField(
            model_name='compraprod',
            name='idArticulos',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='articulos',
        ),
        migrations.AddField(
            model_name='compraprod',
            name='descripcionArticulo',
            field=models.CharField(default=0, help_text='Articulo comprado', max_length=30),
            preserve_default=False,
        ),
    ]
