# Generated by Django 4.2.1 on 2024-03-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0021_remove_articulos_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='identificador_unico',
            field=models.UUIDField(default=1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='cantidad',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='DNI',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='cuit',
            field=models.PositiveBigIntegerField(verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=25, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Venta'),
        ),
    ]
