# Generated by Django 4.2.1 on 2024-03-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appRieVictoria', '0022_articulos_identificador_unico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='identificador_unico',
        ),
    ]
